- id: enforce-action-comments
  name: Enforce Action Comments
  description: "This hook ensures that there are no comments that demand immediate action"
  entry: enforce-action-comments
  language: python
  language_version: python2
  args: [ --tags, 'FIXME,FIX ME']
  files: ''
- id: lfs-large-files
  name: LFS Large Files
  description: "This hooks detects binary files over a certain threshold and ensures that they are LFSed"
  entry: lfs-large-files
  language: python
  language_version: python2
  args: [ --maximum-binary-size, '524288' ] # 512 KiB
  files: ''
- id: yarn-licenses
  name: Yarn Licenses
  description: "This hook analyzes the licenses of packages managed by a yarn.lock file to ensure they meet approved license requirements"
  entry: yarn-licenses
  language: python
  args: [ --approved-licenses, 'MIT,BSD-3-Clause,Public Domain,Unlicense' ]
  files: 'yarn.lock'
